// Auto-generated by @block-resolver/core runtime
import type { ResolverId, ResolverRuntimeContext } from "./../packages/core/src/resolvers/types.ts";
import type { manifestRegistry } from "./manifest.gen";

type Registry = typeof manifestRegistry;

type ExtractProps<TModule> =
  TModule extends { default: (props: infer TProps, ...args: any[]) => any }
    ? TProps extends Record<string, unknown>
      ? TProps
      : Record<string, unknown>
    : Record<string, unknown>;

type ExtractReturn<TModule> =
  TModule extends { default: (...args: any[]) => infer TReturn }
    ? Awaited<TReturn>
    : unknown;

type UnionToIntersection<TUnion> =
  (TUnion extends unknown ? (arg: TUnion) => void : never) extends
  (arg: infer TIntersection) => void
    ? TIntersection
    : never;

type AppResolverIdToProps<TApp> =
  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }
    ? UnionToIntersection<{
        [TResolverType in keyof TResolvers]: {
          [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractProps<
            TResolvers[TResolverType][TResolverId]
          >;
        };
      }[keyof TResolvers]>
    : {};

type AppResolverIdToReturn<TApp> =
  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }
    ? UnionToIntersection<{
        [TResolverType in keyof TResolvers]: {
          [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractReturn<
            TResolvers[TResolverType][TResolverId]
          >;
        };
      }[keyof TResolvers]>
    : {};

export type ResolverIdToPropsMap = UnionToIntersection<
  { [TAppName in keyof Registry]: AppResolverIdToProps<Registry[TAppName]> }[keyof Registry]
>;
export type ResolverIdToReturnMap = UnionToIntersection<
  { [TAppName in keyof Registry]: AppResolverIdToReturn<Registry[TAppName]> }[keyof Registry]
>;

export type ResolverInvokeMap = {
  [TResolverId in keyof ResolverIdToPropsMap & keyof ResolverIdToReturnMap]: {
    props: ResolverIdToPropsMap[TResolverId];
    return: ResolverIdToReturnMap[TResolverId];
  };
};

export type GeneratedResolverId = keyof ResolverInvokeMap & ResolverId;
export type GeneratedInvoke = <TResolverId extends GeneratedResolverId>(
  resolverId: TResolverId,
  props: ResolverInvokeMap[TResolverId]["props"],
) => Promise<ResolverInvokeMap[TResolverId]["return"]>;

export type ResolverContext<
  TExtensions extends object = Record<never, never>,
> = ResolverRuntimeContext<ResolverInvokeMap> & TExtensions;
