// Auto-generated by @block-resolver/core runtime
import * as $0 from "./loaders/echo.ts";
import * as $1 from "./loaders/products/by-query.ts";
import * as $2 from "./loaders/products/list.ts";
import * as $3 from "./loaders/title.ts";
import * as $4 from "./pages/Page.tsx";
import * as $5 from "./sections/header.tsx";
import * as $6 from "./sections/shelf.tsx";
import * as $7 from "./apps/app-example.ts";

export const manifestRegistry = {
  "example": {
    app: {
      name: "example",
    },
    resolvers: {
    loaders: {
      "example/loaders/echo": $0,
      "example/loaders/products/by-query": $1,
      "example/loaders/products/list": $2,
      "example/loaders/title": $3,
    },
    pages: {
      "example/pages/Page": $4,
    },
    sections: {
      "example/sections/header": $5,
      "example/sections/shelf": $6,
    },
    apps: {
      "example/apps/app-example": $7,
    },
    },
  },
} as const;

export default manifestRegistry;
