import { readdir, readFile, writeFile } from "fs/promises";
import { dirname, join, relative } from "path";
import { fileURLToPath, pathToFileURL } from "url";
import { resolverClasses } from "../resolvers/registry";
import type { AppManifest, ManifestRegistry } from "./types";

const APP_CONFIG_FILE = "block-resolver.app.json";
const RESOLVER_TYPES = resolverClasses
  .values()
  .map((resolver) => resolver.type)
  .toArray();
const VALID_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"];

interface AppConfig {
  name: string;
}

interface ResolverFileEntry {
  resolverType: string;
  resolverId: string;
  absoluteFile: string;
}

function normalizePath(path: string): string {
  return path.replaceAll("\\", "/");
}

function stripExtension(filePath: string): string {
  return filePath.replace(/\.(tsx?|jsx?)$/, "");
}

async function walkDirs(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git") continue;

    const absolute = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDirs(absolute)));
      continue;
    }
    files.push(absolute);
  }

  return files;
}

async function getResolverFiles(baseDir: string): Promise<string[]> {
  try {
    const files = await walkDirs(baseDir);
    return files.filter((file) =>
      VALID_EXTENSIONS.some((extension) => file.endsWith(extension)),
    );
  } catch {
    return [];
  }
}

async function readAppConfig(configPath: string): Promise<AppConfig> {
  const raw = await readFile(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<AppConfig>;
  if (!parsed.name || typeof parsed.name !== "string") {
    throw new Error(`App config "${configPath}" must contain a string "name".`);
  }
  return { name: parsed.name };
}

async function collectResolverFileEntries(
  appRoot: string,
  appName: string,
): Promise<ResolverFileEntry[]> {
  const entries: ResolverFileEntry[] = [];

  for (const resolverType of RESOLVER_TYPES) {
    const resolverRoot = join(appRoot, resolverType);
    const resolverFiles = await getResolverFiles(resolverRoot);
    for (const absoluteFile of resolverFiles) {
      const relativeFile = normalizePath(relative(resolverRoot, absoluteFile));
      const normalizedFile = stripExtension(relativeFile);
      entries.push({
        resolverType,
        resolverId: `${appName}/${resolverType}/${normalizedFile}`,
        absoluteFile,
      });
    }
  }

  return entries;
}

async function loadAppManifest(configPath: string): Promise<AppManifest> {
  const appRoot = dirname(configPath);
  const appConfig = await readAppConfig(configPath);
  const resolverFiles = await collectResolverFileEntries(
    appRoot,
    appConfig.name,
  );

  const resolvers: AppManifest["resolvers"] = {};
  for (const entry of resolverFiles) {
    const resolverTypeMap =
      resolvers[entry.resolverType] ?? (resolvers[entry.resolverType] = {});
    const module = await import(pathToFileURL(entry.absoluteFile).href);
    resolverTypeMap[entry.resolverId] = module;
  }

  return {
    app: { name: appConfig.name },
    resolvers,
  };
}

function buildManifestFile(
  appName: string,
  entries: ResolverFileEntry[],
  appRoot: string,
) {
  const importLines: string[] = [];
  const resolverEntriesByType = new Map<string, string[]>();
  let index = 0;

  for (const entry of entries) {
    const importAlias = `$${index++}`;
    const relativeImportPath = `./${normalizePath(relative(appRoot, entry.absoluteFile))}`;
    importLines.push(
      `import * as ${importAlias} from "${relativeImportPath}";`,
    );

    const typeEntries = resolverEntriesByType.get(entry.resolverType) ?? [];
    typeEntries.push(`      "${entry.resolverId}": ${importAlias},`);
    resolverEntriesByType.set(entry.resolverType, typeEntries);
  }

  const resolversByType = Array.from(resolverEntriesByType.entries())
    .map(([type, typeEntries]) =>
      [`    ${type}: {`, ...typeEntries, "    },"].join("\n"),
    )
    .join("\n");

  return [
    "// Auto-generated by @block-resolver/core runtime",
    ...importLines,
    "",
    "export const manifestRegistry = {",
    `  "${appName}": {`,
    "    app: {",
    `      name: "${appName}",`,
    "    },",
    "    resolvers: {",
    resolversByType,
    "    },",
    "  },",
    "} as const;",
    "",
    "export default manifestRegistry;",
    "",
  ].join("\n");
}

function buildManifestTypesFile(appRoot: string) {
  const runtimeDir = dirname(fileURLToPath(import.meta.url));
  const coreResolverTypesPath = join(runtimeDir, "../resolvers/types.ts");
  const coreTypesImportPath = `./${normalizePath(relative(appRoot, coreResolverTypesPath))}`;

  return [
    "// Auto-generated by @block-resolver/core runtime",
    `import type { ResolverId, ResolverRuntimeContext } from "${coreTypesImportPath}";`,
    'import type { manifestRegistry } from "./manifest.gen";',
    "",
    "type Registry = typeof manifestRegistry;",
    "",
    "type ExtractProps<TModule> =",
    "  TModule extends { default: (props: infer TProps, ...args: any[]) => any }",
    "    ? TProps extends Record<string, unknown>",
    "      ? TProps",
    "      : Record<string, unknown>",
    "    : Record<string, unknown>;",
    "",
    "type ExtractReturn<TModule> =",
    "  TModule extends { default: (...args: any[]) => infer TReturn }",
    "    ? Awaited<TReturn>",
    "    : unknown;",
    "",
    "type UnionToIntersection<TUnion> =",
    "  (TUnion extends unknown ? (arg: TUnion) => void : never) extends",
    "  (arg: infer TIntersection) => void",
    "    ? TIntersection",
    "    : never;",
    "",
    "type AppResolverIdToProps<TApp> =",
    "  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }",
    "    ? UnionToIntersection<{",
    "        [TResolverType in keyof TResolvers]: {",
    "          [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractProps<",
    "            TResolvers[TResolverType][TResolverId]",
    "          >;",
    "        };",
    "      }[keyof TResolvers]>",
    "    : {};",
    "",
    "type AppResolverIdToReturn<TApp> =",
    "  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }",
    "    ? UnionToIntersection<{",
    "        [TResolverType in keyof TResolvers]: {",
    "          [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractReturn<",
    "            TResolvers[TResolverType][TResolverId]",
    "          >;",
    "        };",
    "      }[keyof TResolvers]>",
    "    : {};",
    "",
    "export type ResolverIdToPropsMap = UnionToIntersection<",
    "  { [TAppName in keyof Registry]: AppResolverIdToProps<Registry[TAppName]> }[keyof Registry]",
    ">;",
    "export type ResolverIdToReturnMap = UnionToIntersection<",
    "  { [TAppName in keyof Registry]: AppResolverIdToReturn<Registry[TAppName]> }[keyof Registry]",
    ">;",
    "",
    "export type ResolverInvokeMap = {",
    "  [TResolverId in keyof ResolverIdToPropsMap & keyof ResolverIdToReturnMap]: {",
    "    props: ResolverIdToPropsMap[TResolverId];",
    "    return: ResolverIdToReturnMap[TResolverId];",
    "  };",
    "};",
    "",
    "export type GeneratedResolverId = keyof ResolverInvokeMap & ResolverId;",
    "export type GeneratedInvoke = <TResolverId extends GeneratedResolverId>(",
    "  resolverId: TResolverId,",
    '  props: ResolverInvokeMap[TResolverId]["props"],',
    ') => Promise<ResolverInvokeMap[TResolverId]["return"]>;',
    "",
    "export type ResolverContext<",
    "  TExtensions extends object = Record<never, never>,",
    "> = ResolverRuntimeContext<ResolverInvokeMap> & TExtensions;",
    "",
  ].join("\n");
}

export async function writeManifestFilesForRoots(
  roots: string[] = [process.cwd()],
): Promise<void> {
  for (const root of roots) {
    const files = await walkDirs(root);
    const appConfigFiles = files.filter((file) =>
      file.endsWith(APP_CONFIG_FILE),
    );

    for (const configFile of appConfigFiles) {
      const appRoot = dirname(configFile);
      const appConfig = await readAppConfig(configFile);
      const entries = await collectResolverFileEntries(appRoot, appConfig.name);

      await writeFile(
        join(appRoot, "manifest.gen.ts"),
        buildManifestFile(appConfig.name, entries, appRoot),
        "utf8",
      );
      await writeFile(
        join(appRoot, "manifest.types.gen.ts"),
        buildManifestTypesFile(appRoot),
        "utf8",
      );
    }
  }
}

export async function buildManifestRegistryFromRoots(
  roots: string[] = [process.cwd()],
): Promise<ManifestRegistry> {
  const registry: ManifestRegistry = {};

  for (const root of roots) {
    const files = await walkDirs(root);
    const appConfigFiles = files.filter((file) =>
      file.endsWith(APP_CONFIG_FILE),
    );

    for (const configFile of appConfigFiles) {
      const appManifest = await loadAppManifest(configFile);
      registry[appManifest.app.name] = appManifest;
    }
  }

  if (Object.keys(registry).length === 0) {
    throw new Error(`No ${APP_CONFIG_FILE} files found in manifest roots.`);
  }

  return registry;
}
