import { readdir, readFile, writeFile } from "fs/promises";
import { dirname, join, relative } from "path";

const ROOT = process.cwd();
const APP_CONFIG_FILE = "block-resolver.app.json";
const RESOLVER_TYPES = ["loaders", "actions", "sections", "pages"] as const;
const VALID_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"];

interface AppConfig {
  name: string;
}

interface ResolverEntry {
  importPath: string;
  resolverType: string;
  resolverId: string;
}

function normalizeImportPath(path: string): string {
  return path.replaceAll("\\", "/");
}

function stripExtension(filePath: string): string {
  return filePath.replace(/\.(tsx?|jsx?)$/, "");
}

async function walkDirs(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git") {
      continue;
    }

    const absolute = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walkDirs(absolute)));
      continue;
    }

    files.push(absolute);
  }

  return files;
}

async function getResolverFiles(baseDir: string): Promise<string[]> {
  try {
    const files = await walkDirs(baseDir);
    return files.filter((file) =>
      VALID_EXTENSIONS.some((extension) => file.endsWith(extension)),
    );
  } catch {
    return [];
  }
}

async function readAppConfig(configPath: string): Promise<AppConfig> {
  const raw = await readFile(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<AppConfig>;
  if (!parsed.name || typeof parsed.name !== "string") {
    throw new Error(`App config "${configPath}" must contain a string "name".`);
  }

  return {
    name: parsed.name,
  };
}

async function collectResolverEntries(
  appName: string,
  appRoot: string,
  outputRoot: string,
): Promise<ResolverEntry[]> {
  const entries: ResolverEntry[] = [];

  for (const resolverType of RESOLVER_TYPES) {
    const resolverRoot = join(appRoot, resolverType);
    const resolverFiles = await getResolverFiles(resolverRoot);
    for (const absoluteFile of resolverFiles) {
      const relativeFile = normalizeImportPath(
        relative(resolverRoot, absoluteFile),
      );
      const normalizedFile = stripExtension(relativeFile);
      const resolverId = `${appName}/${resolverType}/${normalizedFile}`;
      const importPath = `./${normalizeImportPath(relative(outputRoot, absoluteFile))}`;
      entries.push({
        importPath,
        resolverType,
        resolverId,
      });
    }
  }

  return entries;
}

function buildManifestFile(
  appName: string,
  resolverEntries: ResolverEntry[],
): string {
  const importLines: string[] = [];
  let importIndex = 0;

  const resolverEntriesByType = new Map<string, string[]>();
  for (const entry of resolverEntries) {
    const importName = `$${importIndex++}`;
    importLines.push(`import * as ${importName} from "${entry.importPath}";`);
    const typeEntries = resolverEntriesByType.get(entry.resolverType) ?? [];
    typeEntries.push(`      "${entry.resolverId}": ${importName},`);
    resolverEntriesByType.set(entry.resolverType, typeEntries);
  }

  const resolversByType = Array.from(resolverEntriesByType.entries())
    .map(([type, entries]) => {
      return [`    ${type}: {`, ...entries, "    },"].join("\n");
    })
    .join("\n");

  const appBlock = [
    `  "${appName}": {`,
    "    app: {",
    `      name: "${appName}",`,
    "    },",
    "    resolvers: {",
    resolversByType,
    "    },",
    "  },",
  ].join("\n");

  return [
    "// Auto-generated by scripts/generate-manifest.ts",
    ...importLines,
    "",
    "export const manifestRegistry = {",
    appBlock,
    "} as const;",
    "",
    "export default manifestRegistry;",
    "",
  ].join("\n");
}

function buildManifestTypesFile(coreTypesImportPath: string): string {
  return [
    "// Auto-generated by scripts/generate-manifest.ts",
    `import type { ResolverId, ResolverRuntimeContext } from "@block-resolver/core";`,
    'import type { manifestRegistry } from "./manifest.gen";',
    "",
    "type Registry = typeof manifestRegistry;",
    "",
    "type ExtractProps<TModule> =",
    "  TModule extends { default: (props: infer TProps, ...args: any[]) => any }",
    "    ? TProps extends Record<string, unknown>",
    "      ? TProps",
    "      : Record<string, unknown>",
    "    : Record<string, unknown>;",
    "",
    "type ExtractReturn<TModule> =",
    "  TModule extends { default: (...args: any[]) => infer TReturn }",
    "    ? Awaited<TReturn>",
    "    : unknown;",
    "",
    "type UnionToIntersection<TUnion> =",
    "  (TUnion extends unknown ? (arg: TUnion) => void : never) extends",
    "  (arg: infer TIntersection) => void",
    "    ? TIntersection",
    "    : never;",
    "",
    "type AppResolverIdToProps<TApp> =",
    "  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }",
    "    ? UnionToIntersection<",
    "        {",
    "          [TResolverType in keyof TResolvers]: {",
    "            [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractProps<",
    "              TResolvers[TResolverType][TResolverId]",
    "            >;",
    "          };",
    "        }[keyof TResolvers]",
    "      >",
    "    : {};",
    "",
    "type AppResolverIdToReturn<TApp> =",
    "  TApp extends { resolvers: infer TResolvers extends Record<string, Record<string, unknown>> }",
    "    ? UnionToIntersection<",
    "        {",
    "          [TResolverType in keyof TResolvers]: {",
    "            [TResolverId in keyof TResolvers[TResolverType] & string]: ExtractReturn<",
    "              TResolvers[TResolverType][TResolverId]",
    "            >;",
    "          };",
    "        }[keyof TResolvers]",
    "      >",
    "    : {};",
    "",
    "export type ResolverIdToPropsMap = UnionToIntersection<",
    "  { [TAppName in keyof Registry]: AppResolverIdToProps<Registry[TAppName]> }[keyof Registry]",
    ">;",
    "export type ResolverIdToReturnMap = UnionToIntersection<",
    "  { [TAppName in keyof Registry]: AppResolverIdToReturn<Registry[TAppName]> }[keyof Registry]",
    ">;",
    "",
    "export type ResolverInvokeMap = {",
    "  [TResolverId in keyof ResolverIdToPropsMap & keyof ResolverIdToReturnMap]: {",
    "    props: ResolverIdToPropsMap[TResolverId];",
    "    return: ResolverIdToReturnMap[TResolverId];",
    "  };",
    "};",
    "",
    "export type GeneratedResolverId = keyof ResolverInvokeMap & ResolverId;",
    "export type GeneratedInvoke = <TResolverId extends GeneratedResolverId>(",
    "  resolverId: TResolverId,",
    '  props: ResolverInvokeMap[TResolverId]["props"],',
    ') => Promise<ResolverInvokeMap[TResolverId]["return"]>;',
    "",
    "export type ResolverContext<",
    "  TExtensions extends object = Record<never, never>,",
    "> = ResolverRuntimeContext<ResolverInvokeMap> & TExtensions;",
    "",
  ].join("\n");
}

async function main() {
  const allFiles = await walkDirs(ROOT);
  const appConfigFiles = allFiles.filter((file) =>
    file.endsWith(APP_CONFIG_FILE),
  );
  if (appConfigFiles.length === 0) {
    throw new Error(`No ${APP_CONFIG_FILE} file found.`);
  }

  for (const appConfigFile of appConfigFiles) {
    const appRoot = dirname(appConfigFile);
    const appConfig = await readAppConfig(appConfigFile);
    const resolverEntries = await collectResolverEntries(
      appConfig.name,
      appRoot,
      appRoot,
    );
    const coreTypesImportPath = `./${normalizeImportPath(
      relative(appRoot, join(ROOT, "packages/core/src/resolvers/types.ts")),
    )}`;

    const manifestContent = buildManifestFile(appConfig.name, resolverEntries);
    const typesContent = buildManifestTypesFile(coreTypesImportPath);
    await writeFile(join(appRoot, "manifest.gen.ts"), manifestContent, "utf8");
    await writeFile(
      join(appRoot, "manifest.types.gen.ts"),
      typesContent,
      "utf8",
    );
    console.log(
      `Generated manifests for app "${appConfig.name}" at ${appRoot}`,
    );
  }
}

await main();
