// Auto-generated by @block-resolver/core runtime
import * as $0 from "./loaders/current-token.ts";
import * as $1 from "./loaders/encrypted.ts";
import * as $2 from "./actions/secrets/encrypt.ts";
import * as $3 from "./actions/title.ts";

export const manifestRegistry = {
  "app-example": {
    app: {
      name: "app-example",
    },
    resolvers: {
    loaders: {
      "app-example/loaders/current-token": $0,
      "app-example/loaders/encrypted": $1,
    },
    actions: {
      "app-example/actions/secrets/encrypt": $2,
      "app-example/actions/title": $3,
    },
    },
  },
} as const;

export default manifestRegistry;
